### ISSUE TITLE
Protect reentrancy Attack on Enroll Refund

### ISSUE THREAD

**Issue by bpeters** [destinationdev/eth_enrollment#1]
https://github.com/destinationdev/eth_enrollment/blob/800357df35b6e1b0371a08e82d0b2bf081432099/contracts/Enrollment.sol#L52-L53

The balance state for the account should be set before the transfer.

**Comment by dmill** [comment]
Got it, same issue as the other one. I'll have to remember to start thinking about the changes as a transaction and keep these potential reentrancy issues in mind 👍

**Comment by dmill** [comment]
fixed 1045ce9ed3be6887daffcca2e2d2f9fb442c0719
