### ISSUE TITLE
Wouldn't you want to collect if some amount got into the contract smaller than the spot rate?

### ISSUE THREAD

**Issue by bpeters** [destinationdev/eth_enrollment#2]
https://github.com/destinationdev/eth_enrollment/blob/800357df35b6e1b0371a08e82d0b2bf081432099/contracts/Enrollment.sol#L61

**Comment by dmill** [comment]
I sort of did this deliberately, basically to guard the user against making small withdrawals that will incur repeated gas charges. I figured if they want to withdraw less than a dollar's worth of ether, just empty the contract  (because `empty()` doesn't have a check like this).

**Comment by dmill** [comment]
Yea, probably overengineered. Removed in 8739108b8ff01202b6b48afcc98b060a78867209
