### ISSUE TITLE
Check in max seats is a reasonable number?

### ISSUE THREAD

**Issue by bpeters** [destinationdev/eth_enrollment#3]
https://github.com/destinationdev/eth_enrollment/blob/800357df35b6e1b0371a08e82d0b2bf081432099/contracts/Enrollment.sol#L74-L77

What if max seats is less than the number of people already enrolled?

**Comment by dmill** [comment]
Great point, will add a check there.

**Comment by dmill** [comment]
`require(newMaxSeats >= classSize);` in commit c06c7013df8d32fc1aae7f428af3fd93d1ba65ce
