### ISSUE TITLE
Refund set state before transfer

### ISSUE THREAD

**Issue by bpeters** [destinationdev/eth_enrollment#5]
https://github.com/destinationdev/eth_enrollment/blob/800357df35b6e1b0371a08e82d0b2bf081432099/contracts/Enrollment.sol#L103-L106

Make sure to set state before transfer

**Comment by dmill** [comment]
Do you mean update the state prior to performing the transfer? Like put line 103 at the end? The reason I have it in this order is in case the transfer fails we won't remove the student. However, now that you mention it this stuff is all treated transactionally, right? So The above case would not be possible - it'd just roll back all of those changes anyway?

**Comment by bpeters** [comment]
it's more so to protect against reentrancy, because someone could chain a fall back function to hit it again to get a refund before the state sets back on the contract. They could keep pulling more and more ether out. Remember the example from that talk?

**Comment by dmill** [comment]
Ahhh yea totally I remember. Cool, I'll fix that.

**Comment by dmill** [comment]
fixed in commit b53a484e1508067a6bd5cb61f1188dd424fdac5c
